Branch FEATURE-add-gitignore set up to track remote branch FEATURE-add-gitignore from origin.
Branch master set up to track remote branch master from origin.
Branch FEATURE-add-gitignore set up to track remote branch FEATURE-add-gitignore from origin.
Branch master set up to track remote branch master from origin.
Branch FEATURE-add-gitignore set up to track remote branch FEATURE-add-gitignore from origin.
Branch master set up to track remote branch master from origin.
Branch FEATURE-add-gitignore set up to track remote branch FEATURE-add-gitignore from origin.
Branch master set up to track remote branch master from origin.
Branch FEATURE-add-gitignore set up to track remote branch FEATURE-add-gitignore from origin.
Branch master set up to track remote branch master from origin.
